# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oc_article', '0001_squashed_0019_auto_20160210_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oc_article_ArticleTag_taggeditems', to='oc_article.ArticlePage'),
        ),
        migrations.AlterField(
            model_name='articlepagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_article_articlepagetag_items', to='taggit.Tag'),
        ),
        migrations.AlterField(
            model_name='blockarticlepagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oc_article_BlockArticleTag_taggeditems', to='oc_article.BlockArticlePage'),
        ),
        migrations.AlterField(
            model_name='blockarticlepagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oc_article_blockarticlepagetag_items', to='taggit.Tag'),
        ),
    ]
